language: php

dist: trusty

sudo: required

php:
  - '7.1'

install:
  - composer install --no-interaction

script:
  - /vendor/bin/phpunit
  - docker build -t tanibox/tania -f docker/app/Dockerfile --build-arg BUILD_DATE="$(date +%Y-%m-%d)" .
 
branches:
  only: 
    - development
