app:
    resource: '@AppBundle/Controller/'
    type: annotation

dashboard:
    path: /
    defaults: { _controller: AppBundle:Dashboard:index }
    methods: [GET]

fields:
    path: /fields
    defaults: { _controller: AppBundle:Field:index }
    methods: [GET]

fields_create:
    path: /fields/create
    defaults: { _controller: AppBundle:Field:create }
    methods: [GET, POST]

fields_show:
    path: /fields/{id}
    defaults: { _controller: AppBundle:Field:show}
    requirements:
        id: '\d+'
    methods: [GET, POST]

areas:
    path: /areas
    defaults: { _controller: AppBundle:Area:index }
    methods: [GET]

areas_show:
    path: /areas/{id}
    defaults: { _controller: AppBundle:Area:show }
    requirements:
        id: '\d+'
    methods: [GET]

areas_create:
    path: /areas/create
    defaults: { _controller: AppBundle:Area:create }
    methods: [GET, POST]

reservoirs:
    path: /reservoirs
    defaults: { _controller: AppBundle:Reservoir:index }
    methods: [GET, POST]
